// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | AboutSectionSlice
  | TestimonialSectionSlice
  | FeaturesSectionSlice
  | CtaSectionSlice;

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
  /**
   * Slice Zone field in *About Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: about_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *About Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: about_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *About Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

type BlogPageDocumentDataSlicesSlice = HeroSectionSlice | BlogsSectionSlice;

/**
 * Content for Blog Page documents
 */
interface BlogPageDocumentData {
  /**
   * Slice Zone field in *Blog Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<BlogPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Blog Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: blog_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blog Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: blog_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Blog Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Blog Page document from Prismic
 *
 * - **API ID**: `blog_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BlogPageDocumentData>,
    "blog_page",
    Lang
  >;

type ContactPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | ContactSectionSlice;

/**
 * Content for Contact Page documents
 */
interface ContactPageDocumentData {
  /**
   * Slice Zone field in *Contact Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: contact_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: contact_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Contact Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Contact Page document from Prismic
 *
 * - **API ID**: `contact_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactPageDocumentData>,
    "contact_page",
    Lang
  >;

type GalleryPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | GallerySectionSlice;

/**
 * Content for Gallery Page documents
 */
interface GalleryPageDocumentData {
  /**
   * Slice Zone field in *Gallery Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<GalleryPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Gallery Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: gallery_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Gallery Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: gallery_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Gallery Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Gallery Page document from Prismic
 *
 * - **API ID**: `gallery_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GalleryPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<GalleryPageDocumentData>,
    "gallery_page",
    Lang
  >;

type HomePageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | AboutSectionSlice
  | CtaSectionSlice
  | FeaturesSectionSlice
  | ProcessSectionSlice
  | TestimonialSectionSlice
  | FaqSectionSlice
  | GallerySectionSlice
  | LocationSectionSlice
  | ServicesSectionSlice
  | BlogsSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ServicesPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | ServicesSectionSlice;

/**
 * Content for Services Page documents
 */
interface ServicesPageDocumentData {
  /**
   * Slice Zone field in *Services Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ServicesPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: services_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Services Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: services_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Services Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Services Page document from Prismic
 *
 * - **API ID**: `services_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ServicesPageDocumentData>,
    "services_page",
    Lang
  >;

type TeamPageDocumentDataSlicesSlice = HeroSectionSlice | TeamSectionSlice;

/**
 * Content for Team Page documents
 */
interface TeamPageDocumentData {
  /**
   * Slice Zone field in *Team Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TeamPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Team Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: team_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Team Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: team_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Team Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Team Page document from Prismic
 *
 * - **API ID**: `team_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TeamPageDocumentData>,
    "team_page",
    Lang
  >;

type TestimonialsPageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | TestimonialSectionSlice;

/**
 * Content for Testimonials Page documents
 */
interface TestimonialsPageDocumentData {
  /**
   * Slice Zone field in *Testimonials Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TestimonialsPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Testimonials Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Meta Title [40-65 chars]
   * - **API ID Path**: testimonials_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Testimonials Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Page Description [70-155 chars]
   * - **API ID Path**: testimonials_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Featured Image field in *Testimonials Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials_page.featured_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  featured_image: prismic.ImageField<"large" | "medium" | "thumbnail">;
}

/**
 * Testimonials Page document from Prismic
 *
 * - **API ID**: `testimonials_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialsPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TestimonialsPageDocumentData>,
    "testimonials_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | BlogPageDocument
  | ContactPageDocument
  | GalleryPageDocument
  | HomePageDocument
  | ServicesPageDocument
  | TeamPageDocument
  | TestimonialsPageDocument;

/**
 * Primary content in *AboutSection → Default → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Subheading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * List field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.list
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  list: prismic.RichTextField;

  /**
   * Button field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Swap Layout field in *AboutSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about_section.default.primary.swap_layout
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  swap_layout: prismic.BooleanField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *BlogsSection → Default → Primary*
 */
export interface BlogsSectionSliceDefaultPrimary {
  /**
   * Subheading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *BlogsSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for BlogsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BlogsSection*
 */
type BlogsSectionSliceVariation = BlogsSectionSliceDefault;

/**
 * BlogsSection Shared Slice
 *
 * - **API ID**: `blogs_section`
 * - **Description**: BlogsSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogsSectionSlice = prismic.SharedSlice<
  "blogs_section",
  BlogsSectionSliceVariation
>;

/**
 * Item in *ContactSection → Default → Primary → Items*
 */
export interface ContactSectionSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *ContactSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. Phone, Email, Address
   * - **API ID Path**: contact_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *ContactSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;

  /**
   * Link field in *ContactSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: tel: or mailto:
   * - **API ID Path**: contact_section.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ContactSection → Default → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Subheading field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Contact With Us
   * - **API ID Path**: contact_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Form Title field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;

  /**
   * Help Section Heading field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Need Any Help?
   * - **API ID Path**: contact_section.default.primary.help_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  help_heading: prismic.RichTextField;

  /**
   * Help Section Description field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.help_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  help_description: prismic.RichTextField;

  /**
   * Map Embed URL field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Google Maps embed iframe src
   * - **API ID Path**: contact_section.default.primary.map_embed_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  map_embed_link: prismic.KeyTextField;

  /**
   * Background Image field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * Items field in *ContactSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ContactSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Item in *CTASection → Form → Primary → Items*
 */
export interface CtaSectionSliceFormPrimaryItemsItem {
  /**
   * Icon field in *CTASection → Form → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *CTASection → Form → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *CTASection → Form → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Primary content in *CTASection → Default → Primary*
 */
export interface CtaSectionSliceDefaultPrimary {
  /**
   * Subheading field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary Button field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.primary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary Button field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.secondary_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Background Image field in *CTASection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for CTASection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CTASection → Form → Primary*
 */
export interface CtaSectionSliceFormPrimary {
  /**
   * Subheading field in *CTASection → Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *CTASection → Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *CTASection → Form → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<CtaSectionSliceFormPrimaryItemsItem>>;

  /**
   * Form Title field in *CTASection → Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;
}

/**
 * Form variation for CTASection Slice
 *
 * - **API ID**: `form`
 * - **Description**: CTA with form and feature items
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceForm = prismic.SharedSliceVariation<
  "form",
  Simplify<CtaSectionSliceFormPrimary>,
  never
>;

/**
 * Primary content in *CTASection → Form 2 → Primary*
 */
export interface CtaSectionSliceForm2Primary {
  /**
   * Subheading field in *CTASection → Form 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form2.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *CTASection → Form 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form2.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *CTASection → Form 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form2.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *CTASection → Form 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_section.form2.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Form 2 variation for CTASection Slice
 *
 * - **API ID**: `form2`
 * - **Description**: CTA with heading, description and background image
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSliceForm2 = prismic.SharedSliceVariation<
  "form2",
  Simplify<CtaSectionSliceForm2Primary>,
  never
>;

/**
 * Slice variation for *CTASection*
 */
type CtaSectionSliceVariation =
  | CtaSectionSliceDefault
  | CtaSectionSliceForm
  | CtaSectionSliceForm2;

/**
 * CTASection Shared Slice
 *
 * - **API ID**: `cta_section`
 * - **Description**: CTASection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSectionSlice = prismic.SharedSlice<
  "cta_section",
  CtaSectionSliceVariation
>;

/**
 * Item in *FAQSection → Default → Primary → Items*
 */
export interface FaqSectionSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *FAQSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Question
   * - **API ID Path**: faq_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *FAQSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Answer
   * - **API ID Path**: faq_section.default.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Primary content in *FAQSection → Default → Primary*
 */
export interface FaqSectionSliceDefaultPrimary {
  /**
   * Subheading field in *FAQSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *FAQSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FAQSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *FAQSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<FaqSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for FAQSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FAQSection*
 */
type FaqSectionSliceVariation = FaqSectionSliceDefault;

/**
 * FAQSection Shared Slice
 *
 * - **API ID**: `faq_section`
 * - **Description**: FAQSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSectionSlice = prismic.SharedSlice<
  "faq_section",
  FaqSectionSliceVariation
>;

/**
 * Item in *FeaturesSection → Default → Primary → Items*
 */
export interface FeaturesSectionSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *FeaturesSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *FeaturesSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *FeaturesSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Item in *FeaturesSection → Image → Primary → Items*
 */
export interface FeaturesSectionSliceImagePrimaryItemsItem {
  /**
   * Image field in *FeaturesSection → Image → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Number field in *FeaturesSection → Image → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.items[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField;

  /**
   * Title field in *FeaturesSection → Image → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *FeaturesSection → Image → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Primary content in *FeaturesSection → Default → Primary*
 */
export interface FeaturesSectionSliceDefaultPrimary {
  /**
   * Subheading field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *FeaturesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<FeaturesSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for FeaturesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *FeaturesSection → Image → Primary*
 */
export interface FeaturesSectionSliceImagePrimary {
  /**
   * Subheading field in *FeaturesSection → Image → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *FeaturesSection → Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeaturesSection → Image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *FeaturesSection → Image → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: features_section.image.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<FeaturesSectionSliceImagePrimaryItemsItem>
  >;
}

/**
 * Image variation for FeaturesSection Slice
 *
 * - **API ID**: `image`
 * - **Description**: Feature cards with image, number, title and details
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSectionSliceImage = prismic.SharedSliceVariation<
  "image",
  Simplify<FeaturesSectionSliceImagePrimary>,
  never
>;

/**
 * Slice variation for *FeaturesSection*
 */
type FeaturesSectionSliceVariation =
  | FeaturesSectionSliceDefault
  | FeaturesSectionSliceImage;

/**
 * FeaturesSection Shared Slice
 *
 * - **API ID**: `features_section`
 * - **Description**: FeaturesSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturesSectionSlice = prismic.SharedSlice<
  "features_section",
  FeaturesSectionSliceVariation
>;

/**
 * Item in *GallerySection → Default → Primary → Items*
 */
export interface GallerySectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *GallerySection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<"large">;

  /**
   * Video field in *GallerySection → Default → Primary → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.items[].video
   * - **Documentation**: https://prismic.io/docs/fields/link-to-media
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Category field in *GallerySection → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  category: prismic.SelectField<
    "Therapy" | "Candid" | "Our Doctor" | "Teams" | "Exercise"
  >;
}

/**
 * Primary content in *GallerySection → Default → Primary*
 */
export interface GallerySectionSliceDefaultPrimary {
  /**
   * Subheading field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *GallerySection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<GallerySectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for GallerySection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GallerySectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GallerySection*
 */
type GallerySectionSliceVariation = GallerySectionSliceDefault;

/**
 * GallerySection Shared Slice
 *
 * - **API ID**: `gallery_section`
 * - **Description**: GallerySection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type GallerySectionSlice = prismic.SharedSlice<
  "gallery_section",
  GallerySectionSliceVariation
>;

/**
 * Item in *HeroSection → Default → Primary → Counter*
 */
export interface HeroSectionSliceDefaultPrimaryCounterItem {
  /**
   * Number field in *HeroSection → Default → Primary → Counter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.counter[].number
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  number: prismic.KeyTextField;

  /**
   * Title field in *HeroSection → Default → Primary → Counter*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.counter[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;
}

/**
 * Item in *HeroSection → Form → Primary → Items*
 */
export interface HeroSectionSliceFormPrimaryItemsItem {
  /**
   * Title field in *HeroSection → Form → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Subheading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Video Button field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.video_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Counter field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.counter[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  counter: prismic.GroupField<
    Simplify<HeroSectionSliceDefaultPrimaryCounterItem>
  >;

  /**
   * Image field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Secondary → Primary*
 */
export interface HeroSectionSliceSecondaryPrimary {
  /**
   * Heading field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Background Image field in *HeroSection → Secondary → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.secondary.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Secondary variation for HeroSection Slice
 *
 * - **API ID**: `secondary`
 * - **Description**: Page heading hero (e.g. About, Contact)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceSecondary = prismic.SharedSliceVariation<
  "secondary",
  Simplify<HeroSectionSliceSecondaryPrimary>,
  never
>;

/**
 * Primary content in *HeroSection → Form → Primary*
 */
export interface HeroSectionSliceFormPrimary {
  /**
   * Subheading field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<HeroSectionSliceFormPrimaryItemsItem>>;

  /**
   * Form Title field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.form_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  form_title: prismic.KeyTextField;

  /**
   * Background Image field in *HeroSection → Form → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.form.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Form variation for HeroSection Slice
 *
 * - **API ID**: `form`
 * - **Description**: Hero with checklist and appointment/form (e.g. Team page)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceForm = prismic.SharedSliceVariation<
  "form",
  Simplify<HeroSectionSliceFormPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation =
  | HeroSectionSliceDefault
  | HeroSectionSliceSecondary
  | HeroSectionSliceForm;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *LocationSection → Default → Primary*
 */
export interface LocationSectionSliceDefaultPrimary {
  /**
   * Heading field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Address field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.address
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;

  /**
   * Phone field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.phone
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  phone: prismic.RichTextField;

  /**
   * Email field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  email: prismic.RichTextField;

  /**
   * Map Embed Link field in *LocationSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: location_section.default.primary.map_embed_link
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  map_embed_link: prismic.KeyTextField;
}

/**
 * Default variation for LocationSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LocationSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *LocationSection*
 */
type LocationSectionSliceVariation = LocationSectionSliceDefault;

/**
 * LocationSection Shared Slice
 *
 * - **API ID**: `location_section`
 * - **Description**: LocationSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type LocationSectionSlice = prismic.SharedSlice<
  "location_section",
  LocationSectionSliceVariation
>;

/**
 * Item in *ProcessSection → Default → Primary → Items*
 */
export interface ProcessSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *ProcessSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ProcessSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *ProcessSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Primary content in *ProcessSection → Default → Primary*
 */
export interface ProcessSectionSliceDefaultPrimary {
  /**
   * Subheading field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *ProcessSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: process_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ProcessSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ProcessSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProcessSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProcessSection*
 */
type ProcessSectionSliceVariation = ProcessSectionSliceDefault;

/**
 * ProcessSection Shared Slice
 *
 * - **API ID**: `process_section`
 * - **Description**: ProcessSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProcessSectionSlice = prismic.SharedSlice<
  "process_section",
  ProcessSectionSliceVariation
>;

/**
 * Item in *ServicesSection → Default → Primary → Items*
 */
export interface ServicesSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *ServicesSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ServicesSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *ServicesSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;

  /**
   * Link field in *ServicesSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *ServicesSection → Default → Primary*
 */
export interface ServicesSectionSliceDefaultPrimary {
  /**
   * Subheading field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *ServicesSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: services_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<ServicesSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for ServicesSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServicesSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ServicesSection*
 */
type ServicesSectionSliceVariation = ServicesSectionSliceDefault;

/**
 * ServicesSection Shared Slice
 *
 * - **API ID**: `services_section`
 * - **Description**: ServicesSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesSectionSlice = prismic.SharedSlice<
  "services_section",
  ServicesSectionSliceVariation
>;

/**
 * Item in *TeamSection → Default → Primary → Items → Social Links*
 */
export interface TeamSectionSliceDefaultPrimaryItemsSocialLinksItem {
  /**
   * Type field in *TeamSection → Default → Primary → Items → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.items[].social_links[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"facebook" | "linkedin" | "youtube">;

  /**
   * URL field in *TeamSection → Default → Primary → Items → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.items[].social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *TeamSection → Default → Primary → Items*
 */
export interface TeamSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *TeamSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *TeamSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Name e.g. Dr. Marvin McKin
   * - **API ID Path**: team_section.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Subtitle field in *TeamSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Therapist Expert
   * - **API ID Path**: team_section.default.primary.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Link field in *TeamSection → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Profile / details link
   * - **API ID Path**: team_section.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Social Links field in *TeamSection → Default → Primary → Items*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.items[].social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.NestedGroupField<
    Simplify<TeamSectionSliceDefaultPrimaryItemsSocialLinksItem>
  >;
}

/**
 * Item in *TeamSection → Details → Primary → Social Links*
 */
export interface TeamSectionSliceDetailsPrimarySocialLinksItem {
  /**
   * Type field in *TeamSection → Details → Primary → Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.social_links[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<"facebook" | "youtube" | "linkedin">;

  /**
   * URL field in *TeamSection → Details → Primary → Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *TeamSection → Details → Primary → Accordion Items*
 */
export interface TeamSectionSliceDetailsPrimaryAccordionItemsItem {
  /**
   * Title field in *TeamSection → Details → Primary → Accordion Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. Certifications & Conferences
   * - **API ID Path**: team_section.details.primary.accordion_items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Details field in *TeamSection → Details → Primary → Accordion Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.accordion_items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Primary content in *TeamSection → Default → Primary*
 */
export interface TeamSectionSliceDefaultPrimary {
  /**
   * Subheading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *TeamSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<TeamSectionSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for TeamSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Teams grid (e.g. Team page listing)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TeamSection → Details → Primary*
 */
export interface TeamSectionSliceDetailsPrimary {
  /**
   * Image field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. REHABANA PMR MDS
   * - **API ID Path**: team_section.details.primary.category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Name field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Specialty field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.specialty
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  specialty: prismic.KeyTextField;

  /**
   * Bio field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * Social Links field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<TeamSectionSliceDetailsPrimarySocialLinksItem>
  >;

  /**
   * Accordion Items field in *TeamSection → Details → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team_section.details.primary.accordion_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  accordion_items: prismic.GroupField<
    Simplify<TeamSectionSliceDetailsPrimaryAccordionItemsItem>
  >;
}

/**
 * Details variation for TeamSection Slice
 *
 * - **API ID**: `details`
 * - **Description**: Single team member detail (profile, bio, accordion)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSliceDetails = prismic.SharedSliceVariation<
  "details",
  Simplify<TeamSectionSliceDetailsPrimary>,
  never
>;

/**
 * Slice variation for *TeamSection*
 */
type TeamSectionSliceVariation =
  | TeamSectionSliceDefault
  | TeamSectionSliceDetails;

/**
 * TeamSection Shared Slice
 *
 * - **API ID**: `team_section`
 * - **Description**: TeamSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TeamSectionSlice = prismic.SharedSlice<
  "team_section",
  TeamSectionSliceVariation
>;

/**
 * Item in *TestimonialSection → Default → Primary → Items*
 */
export interface TestimonialSectionSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *TestimonialSection → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Review field in *TestimonialSection → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.items[].review
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  review: prismic.RichTextField;

  /**
   * Name field in *TestimonialSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Info field in *TestimonialSection → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.items[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Item in *TestimonialSection → video → Primary → Items*
 */
export interface TestimonialSectionSliceVideoPrimaryItemsItem {
  /**
   * Image field in *TestimonialSection → video → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video field in *TestimonialSection → video → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.items[].video
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Name field in *TestimonialSection → video → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Details field in *TestimonialSection → video → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.items[].details
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  details: prismic.RichTextField;
}

/**
 * Item in *TestimonialSection → Slider → Primary → Items*
 */
export interface TestimonialSectionSliceSliderPrimaryItemsItem {
  /**
   * Image field in *TestimonialSection → Slider → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.slider.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *TestimonialSection → Slider → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Name e.g. Dr. Mehara Banu
   * - **API ID Path**: testimonial_section.slider.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name: prismic.RichTextField;

  /**
   * Info field in *TestimonialSection → Slider → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. Physical therapy
   * - **API ID Path**: testimonial_section.slider.primary.items[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;

  /**
   * Review field in *TestimonialSection → Slider → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.slider.primary.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;
}

/**
 * Primary content in *TestimonialSection → Default → Primary*
 */
export interface TestimonialSectionSliceDefaultPrimary {
  /**
   * Subheading field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *TestimonialSection → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<TestimonialSectionSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for TestimonialSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialSectionSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TestimonialSection → video → Primary*
 */
export interface TestimonialSectionSliceVideoPrimary {
  /**
   * Subheading field in *TestimonialSection → video → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TestimonialSection → video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *TestimonialSection → video → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *TestimonialSection → video → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.video.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<TestimonialSectionSliceVideoPrimaryItemsItem>
  >;
}

/**
 * video variation for TestimonialSection Slice
 *
 * - **API ID**: `video`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSliceVideo = prismic.SharedSliceVariation<
  "video",
  Simplify<TestimonialSectionSliceVideoPrimary>,
  never
>;

/**
 * Primary content in *TestimonialSection → Slider → Primary*
 */
export interface TestimonialSectionSliceSliderPrimary {
  /**
   * Subheading field in *TestimonialSection → Slider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.slider.primary.subheading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheading: prismic.KeyTextField;

  /**
   * Heading field in *TestimonialSection → Slider → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: e.g. What Our Patients Say
   * - **API ID Path**: testimonial_section.slider.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *TestimonialSection → Slider → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonial_section.slider.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<TestimonialSectionSliceSliderPrimaryItemsItem>
  >;
}

/**
 * Slider variation for TestimonialSection Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Testimonial slider (multiple items, avatar, quote, rating)
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSliceSlider = prismic.SharedSliceVariation<
  "slider",
  Simplify<TestimonialSectionSliceSliderPrimary>,
  never
>;

/**
 * Slice variation for *TestimonialSection*
 */
type TestimonialSectionSliceVariation =
  | TestimonialSectionSliceDefault
  | TestimonialSectionSliceVideo
  | TestimonialSectionSliceSlider;

/**
 * TestimonialSection Shared Slice
 *
 * - **API ID**: `testimonial_section`
 * - **Description**: TestimonialSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialSectionSlice = prismic.SharedSlice<
  "testimonial_section",
  TestimonialSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      BlogPageDocument,
      BlogPageDocumentData,
      BlogPageDocumentDataSlicesSlice,
      ContactPageDocument,
      ContactPageDocumentData,
      ContactPageDocumentDataSlicesSlice,
      GalleryPageDocument,
      GalleryPageDocumentData,
      GalleryPageDocumentDataSlicesSlice,
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ServicesPageDocument,
      ServicesPageDocumentData,
      ServicesPageDocumentDataSlicesSlice,
      TeamPageDocument,
      TeamPageDocumentData,
      TeamPageDocumentDataSlicesSlice,
      TestimonialsPageDocument,
      TestimonialsPageDocumentData,
      TestimonialsPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      BlogsSectionSlice,
      BlogsSectionSliceDefaultPrimary,
      BlogsSectionSliceVariation,
      BlogsSectionSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimaryItemsItem,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      CtaSectionSlice,
      CtaSectionSliceDefaultPrimary,
      CtaSectionSliceFormPrimaryItemsItem,
      CtaSectionSliceFormPrimary,
      CtaSectionSliceForm2Primary,
      CtaSectionSliceVariation,
      CtaSectionSliceDefault,
      CtaSectionSliceForm,
      CtaSectionSliceForm2,
      FaqSectionSlice,
      FaqSectionSliceDefaultPrimaryItemsItem,
      FaqSectionSliceDefaultPrimary,
      FaqSectionSliceVariation,
      FaqSectionSliceDefault,
      FeaturesSectionSlice,
      FeaturesSectionSliceDefaultPrimaryItemsItem,
      FeaturesSectionSliceDefaultPrimary,
      FeaturesSectionSliceImagePrimaryItemsItem,
      FeaturesSectionSliceImagePrimary,
      FeaturesSectionSliceVariation,
      FeaturesSectionSliceDefault,
      FeaturesSectionSliceImage,
      GallerySectionSlice,
      GallerySectionSliceDefaultPrimaryItemsItem,
      GallerySectionSliceDefaultPrimary,
      GallerySectionSliceVariation,
      GallerySectionSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimaryCounterItem,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceSecondaryPrimary,
      HeroSectionSliceFormPrimaryItemsItem,
      HeroSectionSliceFormPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      HeroSectionSliceSecondary,
      HeroSectionSliceForm,
      LocationSectionSlice,
      LocationSectionSliceDefaultPrimary,
      LocationSectionSliceVariation,
      LocationSectionSliceDefault,
      ProcessSectionSlice,
      ProcessSectionSliceDefaultPrimaryItemsItem,
      ProcessSectionSliceDefaultPrimary,
      ProcessSectionSliceVariation,
      ProcessSectionSliceDefault,
      ServicesSectionSlice,
      ServicesSectionSliceDefaultPrimaryItemsItem,
      ServicesSectionSliceDefaultPrimary,
      ServicesSectionSliceVariation,
      ServicesSectionSliceDefault,
      TeamSectionSlice,
      TeamSectionSliceDefaultPrimaryItemsSocialLinksItem,
      TeamSectionSliceDefaultPrimaryItemsItem,
      TeamSectionSliceDefaultPrimary,
      TeamSectionSliceDetailsPrimarySocialLinksItem,
      TeamSectionSliceDetailsPrimaryAccordionItemsItem,
      TeamSectionSliceDetailsPrimary,
      TeamSectionSliceVariation,
      TeamSectionSliceDefault,
      TeamSectionSliceDetails,
      TestimonialSectionSlice,
      TestimonialSectionSliceDefaultPrimaryItemsItem,
      TestimonialSectionSliceDefaultPrimary,
      TestimonialSectionSliceVideoPrimaryItemsItem,
      TestimonialSectionSliceVideoPrimary,
      TestimonialSectionSliceSliderPrimaryItemsItem,
      TestimonialSectionSliceSliderPrimary,
      TestimonialSectionSliceVariation,
      TestimonialSectionSliceDefault,
      TestimonialSectionSliceVideo,
      TestimonialSectionSliceSlider,
    };
  }
}
